twitter:
  consumer_key: dJf7xzF5UWn6LDd2glXy3STtU
  consumer_secret: 5adrTcqdMhO5qLvyNG6NCVqsxRJUqKBe3E6Lf0pYJLJOFWWP30
  access_token: 93828067-VZbHd577ulFGV5R2dqeskrUh2ZcqQi0kj07FfVFOH
  access_token_secret: vrIcvWg2kGarNdRm40SH3bNlRC7NuwAJx7qqjTQzbZNUZ
